# Generated by Django 3.1.7 on 2021-03-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home2',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
