# Generated by Django 3.1.7 on 2021-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0002_auto_20210310_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home1',
            name='image',
            field=models.ImageField(default='', upload_to='sunshine/images'),
        ),
        migrations.AlterField(
            model_name='home2',
            name='image',
            field=models.ImageField(default='', upload_to='sunshine/images'),
        ),
    ]
