# Generated by Django 3.1.7 on 2021-03-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0003_auto_20210310_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Home1',
        ),
        migrations.DeleteModel(
            name='Home2',
        ),
    ]
